# Generated by Django 3.1 on 2020-09-22 03:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0014_auto_20200905_0050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopuser',
            name='activation_key_expires',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 24, 6, 36, 48, 857947)),
        ),
    ]
